version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend-net

  consumer-service:
    build:
      context: ../consumer-service
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: Consumers
    ports:
      - "3008:3008"
    depends_on:
      - postgres
    networks:
      - backend-net

  policy-service:
    build:
      context: ../policy-service
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: Policy
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - backend-net

  user-service:
    build:
      context: ../user-service
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: Users
    ports:
      - "3005:3005"
    depends_on:
      - postgres
    networks:
      - backend-net

volumes:
  pgdata:

networks:
  backend-net:
    driver: bridge